### ISSUE TITLE
did-fail-load is reported when using hot reload

### ISSUE THREAD

**Issue by crackcomm** [reactivemarkets/desktop#598]
Hey, I tried developing an application using desktop and I had two issues so far: I'm not able to change security policy when installed desktop globally using npm to use `http` and second most important is a bug in error handling that causes a window with message `-3: ` to appear with only choice to close the window.

I had to [comment](https://github.com/reactivemarkets/desktop/blob/main/packages/desktop-core/src/main/windowing/factory/failedToLoadWindowFactory.ts) out this dialog box and I'm able to develop with hot reloads now.

**Comment by markmcdowell** [comment]
Hi, that’s interesting -3 appears to be “the operation was aborted” I could see that happening when developing. To reproduce I just need to enable hot reload?

you can modify the security policy if you go to the install location and change the app-defaults.yaml
Although it may be better to add a command line option to allow insecure requests whilst developing.

**Comment by crackcomm** [comment]
It can be reproduced with simple `create-react-app` application.

I will use the app-defaults.yml. Information about it in README or a command line flag would be useful too.
